name: coldstart
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.3=py_1
  - asn1crypto=0.24.0=py36_3
  - automat=0.7.0=py_1
  - bleach=2.1.4=py_1
  - cffi=1.11.5=py36h5e8e0c9_1
  - constantly=15.1.0=py_0
  - cryptography=2.3.1=py36hdffb7b8_0
  - cryptography-vectors=2.3.1=py36_0
  - entrypoints=0.2.3=py36_2
  - gmp=6.1.2=hfc679d8_0
  - html5lib=1.0.1=py_0
  - hyperlink=17.3.1=py_0
  - idna=2.7=py36_2
  - incremental=17.5.0=py_0
  - ipykernel=4.9.0=py36_0
  - jinja2=2.10=py_1
  - jsonschema=2.6.0=py36_2
  - jupyter_client=5.2.3=py_1
  - jupyter_contrib_core=0.3.3=py_2
  - jupyter_contrib_nbextensions=0.5.0=py36_0
  - jupyter_core=4.4.0=py_0
  - jupyter_highlight_selected_word=0.2.0=py36_0
  - jupyter_latex_envs=1.4.4=py36_0
  - jupyter_nbextensions_configurator=0.4.0=py36_0
  - libsodium=1.0.16=h470a237_1
  - libxslt=1.1.32=h88dbc4e_2
  - lxml=4.2.4=py36hc9114bc_0
  - markupsafe=1.0=py36h470a237_1
  - mistune=0.8.3=py36h470a237_2
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py_1
  - notebook=5.6.0=py36_1
  - pandoc=2.2.2=1
  - pandocfilters=1.4.2=py_1
  - prometheus_client=0.3.0=py_0
  - pyasn1=0.4.4=py_0
  - pyasn1-modules=0.2.1=py_0
  - pycparser=2.18=py_1
  - pyhamcrest=1.9.0=py_2
  - pyopenssl=18.0.0=py36_0
  - pyzmq=17.1.2=py36hae99301_0
  - send2trash=1.5.0=py_0
  - service_identity=17.0.0=py_0
  - terminado=0.8.1=py36_1
  - testpath=0.3.1=py36_1
  - twisted=18.7.0=py36h470a237_1
  - webencodings=0.5.1=py_1
  - zeromq=4.2.5=hfc679d8_5
  - zope.interface=4.5.0=py36h470a237_1
  - _tflow_1100_select=0.0.1=gpu
  - absl-py=0.4.1=py36_0
  - astor=0.7.1=py36_0
  - astroid=2.0.4=py36_0
  - atomicwrites=1.2.1=py36_0
  - attrs=18.2.0=py36h28b3542_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - ca-certificates=2018.03.07=0
  - cairo=1.14.12=h8948797_3
  - certifi=2018.10.15=py36_0
  - cudatoolkit=9.2=0
  - cudnn=7.2.1=cuda9.2_0
  - cupti=9.2.148=0
  - cycler=0.10.0=py36h93f1223_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.0=py36_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.5=h7b6447c_0
  - gast=0.2.0=py36_0
  - glib=2.56.2=hd408876_0
  - graphite2=1.3.12=h23475e2_2
  - graphviz=2.40.1=h21bd128_2
  - grpcio=1.12.1=py36hdbcaa40_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.8.0=py36h989c5e5_3
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2018.0.3=0
  - ipython=6.5.0=py36_0
  - ipython_genutils=0.2.0=py36hb52b0d5_0
  - ipywidgets=7.4.1=py36_0
  - isort=4.3.4=py36_0
  - jedi=0.12.1=py36_0
  - joblib=0.12.5=py36_0
  - jpeg=9b=h024ee3a_2
  - keras=2.2.0=0
  - keras-applications=1.0.2=py36_0
  - keras-base=2.2.0=py36_0
  - keras-preprocessing=1.0.1=py36_0
  - kiwisolver=1.0.1=py36hf484d3e_0
  - lazy-object-proxy=1.3.1=py36h14c3975_2
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.34=hb9fc6fc_0
  - libprotobuf=3.6.0=hdbcaa40_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.9=he85c1e1_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - markdown=2.6.11=py36_0
  - matplotlib=2.2.3=py36hb69df0a_0
  - mccabe=0.6.1=py36_1
  - mkl=2018.0.3=1
  - mkl_fft=1.0.4=py36h4414c95_1
  - mkl_random=1.0.1=py36h4414c95_1
  - more-itertools=4.3.0=py36_0
  - ncurses=6.1=hf484d3e_0
  - numpy=1.15.1=py36h1d66e8a_0
  - numpy-base=1.15.1=py36h81de0dd_0
  - openssl=1.0.2p=h14c3975_0
  - pandas=0.23.4=py36h04863e7_0
  - pango=1.42.4=h049681c_0
  - parso=0.3.1=py36_0
  - patsy=0.5.0=py36_0
  - pcre=8.42=h439df22_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.4=py36h63277f8_0
  - pip=10.0.1=py36_0
  - pixman=0.34.0=hceecf20_3
  - pluggy=0.7.1=py36h28b3542_0
  - prompt_toolkit=1.0.15=py36h17d85b1_0
  - protobuf=3.6.0=py36hf484d3e_0
  - ptyprocess=0.6.0=py36_0
  - py=1.6.0=py36_0
  - pydot=1.2.4=py36_0
  - pygments=2.2.0=py36_0
  - pylint=2.1.1=py36_0
  - pyparsing=2.2.0=py36_1
  - pyqt=5.9.2=py36h22d08a2_1
  - pytest=3.7.4=py36_0
  - python=3.6.6=hc3d631a_0
  - python-dateutil=2.7.3=py36_0
  - pytz=2018.5=py36_0
  - pyyaml=3.13=py36h14c3975_0
  - qt=5.9.6=h8703b6f_2
  - readline=7.0=h7b6447c_5
  - rope=0.11.0=py36_0
  - scikit-learn=0.19.1=py36hedc7406_0
  - scipy=1.1.0=py36hfa4b5c9_1
  - seaborn=0.9.0=py36_0
  - setuptools=40.2.0=py36_0
  - simplegeneric=0.8.1=py36_2
#  - sip=4.19.12=py36he6710b0_0
  - sip
  - six=1.11.0=py36_1
  - sqlite=3.24.0=h84994c4_0
  - statsmodels=0.9.0=py36h035aef0_0
  - tensorboard=1.10.0=py36hf484d3e_0
  - tensorflow=1.10.0=gpu_py36hcebf108_0
  - tensorflow-base=1.10.0=gpu_py36had579c0_0
  - tensorflow-gpu=1.10.0=hf154084_0
  - termcolor=1.1.0=py36_1
  - tk=8.6.8=hbc83047_0
  - tornado=5.1=py36h14c3975_0
  - tqdm=4.25.0=py36h28b3542_0
  - traitlets=4.3.2=py36_0
  - typed-ast=1.1.0=py36h14c3975_0
  - wcwidth=0.1.7=py36hdf4376a_0
  - werkzeug=0.14.1=py36_0
  - wheel=0.31.1=py36_0
  - widgetsnbextension=3.4.1=py36_0
  - wrapt=1.10.11=py36h14c3975_2
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=ha838bed_2

